return {
  version = "1.9",
  luaversion = "5.1",
  tiledversion = "1.9.1",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 80,
  height = 12,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 6,
  nextobjectid = 383,
  properties = {},
  tilesets = {
    {
      name = "DnN_LevelTiles",
      firstgid = 1,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 7,
      image = "DnN_LevelTiles.png",
      imagewidth = 224,
      imageheight = 256,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 56,
      tiles = {}
    },
    {
      name = "hero",
      firstgid = 57,
      class = "",
      tilewidth = 112,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 2,
      tiles = {
        {
          id = 0,
          class = "element",
          image = "../../images/DnN_Player/DnN_Player_Idle_0001.png",
          width = 112,
          height = 64
        },
        {
          id = 1,
          image = "../../images/DnN_Player/DnN_PlayerBullet_HitFX_0001.png",
          width = 32,
          height = 32
        }
      }
    },
    {
      name = "enemy",
      firstgid = 59,
      class = "",
      tilewidth = 81,
      tileheight = 73,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 8,
      tiles = {
        {
          id = 0,
          image = "../../images/DnN_Enemy/DnN_Enemy_Idle_0001.png",
          width = 64,
          height = 64
        },
        {
          id = 1,
          image = "../../images/DnN_Enemy/DnN_Enemy_Idle_0002.png",
          width = 64,
          height = 64
        },
        {
          id = 2,
          image = "../../images/DnN_Enemy/DnN_Enemy_Idle_0003.png",
          width = 64,
          height = 64
        },
        {
          id = 3,
          image = "../../images/DnN_Enemy/DnN_Enemy_Idle_0004.png",
          width = 64,
          height = 64
        },
        {
          id = 4,
          image = "../../images/DnN_Level/prop1.png",
          width = 81,
          height = 73
        },
        {
          id = 5,
          image = "../../images/DnN_Level/prop2.png",
          width = 74,
          height = 44
        },
        {
          id = 6,
          image = "../../images/DnN_Level/props3.png",
          width = 59,
          height = 59
        },
        {
          id = 7,
          image = "../../images/DnN_Level/props4.png",
          width = 58,
          height = 58
        }
      }
    },
    {
      name = "hud",
      firstgid = 67,
      class = "",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 5,
      image = "../../images/DnN_HUD.png",
      imagewidth = 160,
      imageheight = 32,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 5,
      tiles = {}
    },
    {
      name = "bossTile",
      firstgid = 72,
      class = "",
      tilewidth = 133,
      tileheight = 128,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 2,
      tiles = {
        {
          id = 0,
          image = "../../images/DnN_Boss/DnN_BossDreamForm_Attack_0005.png",
          width = 133,
          height = 128
        },
        {
          id = 1,
          image = "../../images/DnN_Boss/DnN_BossNightmareForm_IdleMove_0002.png",
          width = 133,
          height = 128
        }
      }
    },
    {
      name = "eyes",
      firstgid = 74,
      class = "",
      tilewidth = 256,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 2,
      image = "../../images/DnN_Boss/eyes.png",
      imagewidth = 512,
      imageheight = 32,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 256,
        height = 32
      },
      properties = {},
      wangsets = {},
      tilecount = 2,
      tiles = {}
    }
  },
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "walls",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 22,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 0,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 37,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 23,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 0,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 37,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 24,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 0,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 37,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 25,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 0,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 37,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 26,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 0,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 37,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 27,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 0,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 37,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 28,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 0,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 37,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 29,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 0,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 37,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 63,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 0,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 30,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 80,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 32,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 81,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 64,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 82,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 96,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 83,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 32,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 84,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 64,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 88,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 128,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 91,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 352,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 92,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 320,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 95,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 288,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 96,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 256,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 99,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 224,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 100,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 192,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 103,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 160,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 106,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 32,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 39,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 107,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 64,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 40,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 108,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 96,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 39,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 109,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 128,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 39,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 110,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 160,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 39,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 111,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 192,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 39,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 112,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 224,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 39,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 113,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 256,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 39,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 114,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 288,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 39,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 115,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 320,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 39,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 116,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 352,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 40,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 117,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 352,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 47,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 132,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 32,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 133,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 64,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 134,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 96,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 135,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 128,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 136,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 160,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 137,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 192,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 138,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 256,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 139,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 224,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 140,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 288,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 141,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 320,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 142,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 352,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 47,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 145,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 384,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 17,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 147,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 384,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 17,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 148,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 384,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 17,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 149,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 384,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 17,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 150,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 384,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 17,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 151,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 416,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 152,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 448,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 153,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 480,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 154,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 384,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 156,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 544,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 157,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 576,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 158,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 416,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 159,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 448,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 160,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 480,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 161,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 512,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 162,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 512,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 163,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 544,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 164,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 576,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 165,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 576,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 167,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 544,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 168,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 512,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 169,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 480,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 170,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 448,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 171,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 416,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 172,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 416,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 173,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 416,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 174,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 448,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 175,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 448,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 176,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 480,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 177,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 480,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 178,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 512,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 179,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 512,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 180,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 544,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 181,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 576,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 182,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 576,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 183,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 544,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 184,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 544,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 185,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 576,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 187,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 512,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 190,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 608,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 191,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 576,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 192,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 544,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 193,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 512,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 194,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 480,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 195,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 448,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {
            ["bodyType"] = "static",
            ["friction"] = 0
          }
        },
        {
          id = 246,
          name = "player",
          class = "element",
          shape = "rectangle",
          x = 129.364,
          y = 278.606,
          width = 112,
          height = 64,
          rotation = 0,
          gid = 57,
          visible = true,
          properties = {
            ["bodyType"] = "dynamic"
          }
        },
        {
          id = 255,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 608,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 256,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 640,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 257,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 672,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 263,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 608,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {}
        },
        {
          id = 264,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 640,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {}
        },
        {
          id = 265,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 672,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {}
        },
        {
          id = 266,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 672,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {}
        },
        {
          id = 267,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 640,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {}
        },
        {
          id = 268,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 608,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {}
        },
        {
          id = 269,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 608,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {}
        },
        {
          id = 270,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 640,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {}
        },
        {
          id = 271,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 672,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {}
        },
        {
          id = 272,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 672,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {}
        },
        {
          id = 273,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 640,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {}
        },
        {
          id = 274,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 608,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {}
        },
        {
          id = 275,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 608,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {}
        },
        {
          id = 276,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 640,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {}
        },
        {
          id = 277,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 672,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {}
        },
        {
          id = 293,
          name = "eyes",
          class = "",
          shape = "rectangle",
          x = 192,
          y = 96,
          width = 256,
          height = 32,
          rotation = 0,
          gid = 74,
          visible = true,
          properties = {}
        },
        {
          id = 298,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2528,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 26,
          visible = true,
          properties = {}
        },
        {
          id = 299,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2496,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 300,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2464,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 301,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2432,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 302,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2368,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 303,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2400,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 304,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2304,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 305,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2336,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 306,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2272,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 307,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2208,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 308,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2240,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 309,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2176,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 310,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2144,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 311,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2112,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 312,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2080,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 313,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2048,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 314,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1984,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 315,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2016,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 316,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1952,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 317,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1920,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 318,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1856,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 319,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1888,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 320,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1824,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 321,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1792,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 322,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1760,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 323,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1728,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 324,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1696,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 325,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1632,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 326,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1664,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 327,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1600,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 328,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1568,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 329,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1536,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 330,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1504,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 331,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1472,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 332,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1440,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 333,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1408,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 334,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1344,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 335,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1376,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 336,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1312,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 337,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1280,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 338,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1248,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 339,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1216,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 340,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1184,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 341,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1152,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 342,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1120,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 343,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1088,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 344,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1056,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 345,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 1024,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 346,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 992,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 347,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 960,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 349,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 928,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 350,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 896,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 351,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 864,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 352,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 832,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 353,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 800,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 354,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 768,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 355,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 736,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 356,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 704,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 25,
          visible = true,
          properties = {}
        },
        {
          id = 358,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2528,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 19,
          visible = true,
          properties = {}
        },
        {
          id = 359,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2528,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 19,
          visible = true,
          properties = {}
        },
        {
          id = 360,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2528,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 19,
          visible = true,
          properties = {}
        },
        {
          id = 361,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2528,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 19,
          visible = true,
          properties = {}
        },
        {
          id = 362,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2528,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 19,
          visible = true,
          properties = {}
        },
        {
          id = 363,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2528,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 19,
          visible = true,
          properties = {}
        },
        {
          id = 364,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2528,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 19,
          visible = true,
          properties = {}
        },
        {
          id = 365,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2528,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 19,
          visible = true,
          properties = {}
        },
        {
          id = 366,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2528,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 19,
          visible = true,
          properties = {}
        },
        {
          id = 367,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2528,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 19,
          visible = true,
          properties = {}
        },
        {
          id = 370,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 2528,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 378,
          name = "",
          class = "",
          shape = "rectangle",
          x = 448,
          y = 170,
          width = 81,
          height = 73,
          rotation = 0,
          gid = 63,
          visible = true,
          properties = {}
        },
        {
          id = 379,
          name = "",
          class = "",
          shape = "rectangle",
          x = 542,
          y = 144,
          width = 74,
          height = 44,
          rotation = 0,
          gid = 64,
          visible = true,
          properties = {}
        },
        {
          id = 380,
          name = "",
          class = "",
          shape = "rectangle",
          x = 544,
          y = 64,
          width = 59,
          height = 59,
          rotation = 0,
          gid = 65,
          visible = true,
          properties = {}
        },
        {
          id = 381,
          name = "",
          class = "",
          shape = "rectangle",
          x = 32,
          y = 224,
          width = 58,
          height = 58,
          rotation = 0,
          gid = 66,
          visible = true,
          properties = {}
        },
        {
          id = 382,
          name = "",
          class = "",
          shape = "rectangle",
          x = 288,
          y = 256,
          width = 58,
          height = 58,
          rotation = 0,
          gid = 66,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "hud",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 240,
          name = "",
          class = "hud",
          shape = "rectangle",
          x = 1,
          y = 34,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 67,
          visible = true,
          properties = {}
        },
        {
          id = 241,
          name = "",
          class = "hud",
          shape = "rectangle",
          x = 32,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 68,
          visible = true,
          properties = {}
        },
        {
          id = 242,
          name = "",
          class = "hud",
          shape = "rectangle",
          x = 64,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 69,
          visible = true,
          properties = {}
        },
        {
          id = 278,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 704,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 279,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 736,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 280,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 768,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 281,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 800,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 282,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 704,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 283,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 736,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 14,
          visible = true,
          properties = {}
        },
        {
          id = 285,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 704,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 286,
          name = "",
          class = "wall",
          shape = "rectangle",
          x = 736,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 21,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
